name: ERM Platform CD

on:
  push:
    branches: [main]

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build:frontend

      - name: Build backend
        run: npm run build:backend

      - name: Deploy to production
        run: scripts/deploy-production.sh
        env:
          PRODUCTION_SERVER_IP: ${{ secrets.PRODUCTION_SERVER_IP }}
          PRODUCTION_SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
          PRODUCTION_USER: ${{ secrets.PRODUCTION_USER }}

      - name: Run database migrations
        run: npm run migrate

      - name: Verify deployment
        run: curl -f https://${{ secrets.PRODUCTION_DOMAIN }}/api/health || exit 1